### ISSUE TITLE
Unable to map Nested source attribute to nested Destination Attribute

### ISSUE THREAD

**Issue by NitinGadgil** [xebia-france/selma#139]
I am trying to map 2 Model objects & as part of that using @Field annotation. Whenever I try to map nested source attribute to nested destination attribute, it throws an error giving below message : 
**Bad custom field to field mapping: both source and destination can not be embedded**

Why is this not supported ? For the object transformation I am working on, this is the most important thing.

Please suggest.

**Comment by NitinGadgil** [comment]
waiting for some kind of suggestion. Thanks in advance.

**Comment by slemesle** [comment]
Hi @NitinGadgil, 

This is due to the way Selma works, it maps from a bean to another one. Selma build a specific method for each bean being mapped in the hierarchy. So it needs to start from a root point. 

For this specific requirement, you can use an interceptor  on root bean and pass the value from the embedded one to another. 

Another way would be to create a mapping method for the two embedded beans. 

Can you share a sample of the bean hierarchy you want to transform ?

**Comment by NitinGadgil** [comment]
My mapping Requirement is like this : 
**From**  POJO1 --> List<POJO 2> -->first POJO2-->List<POJO3>-->first POJO3-->POJO4 --->value 
**To**      POJO5 --> -->POJO6 --->value

**Comment by slemesle** [comment]
Sorry but this sounds like a business logic and not a stupid mapping. 
Selma won't be able to handle such a logic. 
The best thing you have to do is implement it on your own.

**Comment by santhoshNS** [comment]
Hi selmesle,
I trying to map source bean array to a destination list collection. Is it possible.? Explain me about this.
thanks in advance.
