### ISSUE TITLE
Handle of cycles [question]

### ISSUE THREAD

**Issue by danjee** [xebia-france/selma#187]
How does Selma handles graph cycles? 
Thanks

**Comment by slemesle** [comment]
Hi,
Selma builds a cache of visited instances and tries to get the instance from the cache each time. 
The first time, Selma will just put the instance as key in cache and the mapping result as value. The second time, Selma will return the already mapped value and use it for it's mapping instead of rebuilding the object.

**Comment by danjee** [comment]
Thanks
