### ISSUE TITLE
Can't initialize the selma mapper into field declaration of the custom mapper.

### ISSUE THREAD

**Issue by seblm** [xebia-france/selma#53]
Given a mapper `SelmaMapper` that declares a custom mapper `CustomSelmaMapper`.
Given this `CustomSelmaMapper` wants to use `SelmaMapper` again.
If `CustomSelmaMapper` initialize `SelmaMapper` into a field declaration,
When `SelmaMapper` is first used and initialized,
Then there is a `StackOverflowError`.

You can find a failing test on [this project](https://github.com/seblm/code-samples/tree/master/selma-custom-mapper).

**Comment by slemesle** [comment]
I see 2 possible solutions for this to work correctly as a supported feature in Selma:
 * Add the source mapper as a parameter of the custom mapper either in constructor or mapping method
 * Use an abstract class for the mapper contract instead of an interface and consider non abstract methods as custom mapping methods.

The second one will be supported one day it is a feature we want to implement in Selma but the first one is not expected for now. 

Any idea would be appreciated, also please tell me what would be your preferred solution.

**Comment by seblm** [comment]
I also prefer the second one. I think that this _issue_ is not a blocker at all. I can close it without any esitation
